/**
 * What the standard calls a code point: COMBINING DIAERESIS for U+0308.
 *
 * A glyph's own name answers "what is this called in this font", which for a
 * mark is `uni0308` and for an unencoded alternate is whatever the designer
 * typed. It does not answer "which mark is this", and the browser is full of
 * cells where that is the only question being asked — most of all just after
 * the missing glyphs of a block have been added and a screenful of empty boxes
 * appears at once.
 *
 * The table is generated by `tools/unicode-names/make_names.py` and sits in a
 * module of its own, imported only when a name is first wanted: it is four
 * hundred kilobytes, and a session that never hovers a cell should never pay
 * for it. Everything here is therefore asynchronous once, and synchronous after —
 * {@link unicodeName} answers from the table when it has arrived and `null`
 * before that, so a caller can draw immediately and again when it is there.
 */

let names: Map<number, string> | null = null;
let loading: Promise<Map<number, string>> | null = null;

/**
 * The name of a code point, or `null` for one the table has not got.
 *
 * Also `null` before the table has been loaded, which is why this is paired
 * with {@link loadUnicodeNames} rather than being the only way in.
 */
export function unicodeName(codePoint: number): string | null {
  return names?.get(codePoint) ?? null;
}

/** Whether the table is there, so a caller can decide whether to wait. */
export function unicodeNamesReady(): boolean {
  return names !== null;
}

/**
 * Load the table, once.
 *
 * Asked for by everything that wants a name, and the second caller onwards gets
 * the first one's promise. A failure to unpack — a browser without
 * `DecompressionStream`, which is not one this application runs in, but also a
 * module that did not arrive — leaves an empty table rather than throwing: a
 * missing name is a tooltip with one line fewer, not an error anybody can act
 * on.
 */
export async function loadUnicodeNames(): Promise<Map<number, string>> {
  if (names !== null) return names;
  loading ??= read().then((table) => {
    names = table;
    return table;
  });
  return loading;
}

async function read(): Promise<Map<number, string>> {
  try {
    const { UNICODE_NAME_DATA } = await import("./unicode-names-data.js");
    return parse(await inflate(UNICODE_NAME_DATA));
  } catch {
    return new Map();
  }
}

/** `0308 COMBINING DIAERESIS` a line at a time, as the generator writes it. */
function parse(text: string): Map<number, string> {
  const table = new Map<number, string>();
  for (const line of text.split("\n")) {
    const space = line.indexOf(" ");
    if (space <= 0) continue;
    table.set(Number.parseInt(line.slice(0, space), 16), line.slice(space + 1));
  }
  return table;
}

async function inflate(encoded: string): Promise<string> {
  // The generator wraps the base64 across lines to keep the file diffable.
  const binary = atob(encoded.replace(/\n/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);

  // Through a `Response` rather than a `Blob`, which is not only shorter: a
  // `Blob` and a `DecompressionStream` can come from different realms — they do
  // under jsdom — and piping one into the other then fails for a reason that
  // looks nothing like the cause.
  const body = new Response(bytes).body;
  if (body === null) throw new Error("no body to unpack");
  return new Response(body.pipeThrough(new DecompressionStream("deflate-raw"))).text();
}
