"""Write the Unicode character names the glyph browser shows.

A cell in the browser says `uni0308`, which is the glyph's name and not an
answer to "which mark is this". The name the standard gives it — COMBINING
DIAERESIS — is the answer, and nothing in a font file carries it, so it is
generated here and shipped with the application.

The names come from Python's own `unicodedata`, which is the Unicode Character
Database as CPython ships it, so no network and no dependency is involved.

Every named code point of the Basic Multilingual Plane is written. Stopping at
the blocks the browser lists was tempting and wrong: those are the blocks it
*filters* by, and a font may encode anything, so the one glyph with no name
would be whichever one somebody was puzzled by. Beyond the BMP the table
quadruples for characters a type designer meets far less often, so it stops
there, and a code point past it simply has no name to show.

The table is deflated and written as base64 into a TypeScript module of its
own, which the application loads only when a name is first asked for. Raw, it
is well over a megabyte of extremely repetitive text; deflate takes that to a
fraction of it, and `DecompressionStream` unpacks it in the browser and in Node
alike.
"""

import base64
import os
import unicodedata
import zlib

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
out_ts = os.path.join(root, "packages", "catalog", "src", "unicode-names-data.ts")

# One line per named code point: the point in hex, a space, the name. Ascending,
# with unnamed points simply left out.
lines = []
for code_point in range(0x10000):
    name = unicodedata.name(chr(code_point), "")
    if name:
        lines.append(f"{code_point:x} {name}")

text = "\n".join(lines).encode("utf8")
# Raw deflate, which is what `DecompressionStream("deflate-raw")` reads.
packed = zlib.compress(text, 9)[2:-4]
encoded = base64.b64encode(packed).decode("ascii")

# Wrapped, because a single line of four hundred thousand characters is a file
# no editor and no diff handles gracefully.
wrapped = "\n".join(encoded[i : i + 100] for i in range(0, len(encoded), 100))

module = f'''// Generated by tools/unicode-names/make_names.py. Do not edit.
//
// The Unicode names of every named code point in the Basic Multilingual Plane,
// deflated and base64-encoded: {len(lines):,} names, {len(text):,} bytes of text
// in {len(encoded):,} characters here. Unpacked by unicode-names.ts, which is
// the only thing that should import this.
//
// The names are from the Unicode Character Database, by way of Python's
// unicodedata. See THIRD_PARTY_NOTICES.txt.

export const UNICODE_NAME_DATA = `{wrapped}`;
'''

with open(out_ts, "w", encoding="utf8", newline="\n") as f:
    f.write(module)

print(
    f"{out_ts}: {len(lines):,} names, {len(text):,} bytes of text, "
    f"{len(encoded):,} characters written"
)
