/**
 * Font binaries, as base64, built once with opentype.js and pasted here.
 *
 * Generated rather than built at test time on purpose: `font-io` exists so that
 * nothing outside it knows which parser is in use, and exporting the parser
 * handle so a test could construct a font would defeat exactly the
 * encapsulation the package is for. A fixture costs a few kilobytes and keeps
 * the boundary intact.
 *
 * THREE has .notdef plus A, B and C. DUPES names two different glyphs "A", the
 * way a damaged font does, so the importer's renaming can be exercised.
 */

const THREE =
  "T1RUTwAKAIAAAwAgQ0ZGIKtiJ2IAAATgAAAAuU9TLzJpKmOJAAABEAAAAGBjbWFwAAwAdgAABJQAAAAsaGVhZC5Wo5oA" +
  "AACsAAAANmhoZWEDIgFFAAAA5AAAACRobXR4CAwAAAAABZwAAAAQbHRhZ2V+AAQAAAWsAAAAEm1heHAABFAAAAABCAAA" +
  "AAZuYW1lBcAD8gAAAXAAAAMhcG9zdAADAAAAAATAAAAAIAABAAAAAQAAB6FiFF8PPPUAAwPoAAAAAOa6MBMAAAAA5row" +
  "EwBQAAABfAKUAAAAAwACAAAAAAAAAAEAAAMg/zgAAAIIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAEAABQAAAEAAAAAwII" +
  "AfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAWFhYWABAAEEAQwMg/zgA" +
  "AAKUAAAAAAABAAAAAAGQApQAAAAAAAAAAAAzAmoAAAAEAAAAAAACAC4AAAAEAAAAAQAQAAAAAAAEAAAAAgAOABAAAAAE" +
  "AAAAAwAmAFQAAAAEAAAABAAgAB4AAAAEAAAABQAWAD4AAAAEAAAABgAeAAAAAAAEAAAABwACAC4AAAAEAAAACAACAC4A" +
  "AAAEAAAACQACAC4AAAAEAAAACgACAC4AAAAEAAAACwACAC4AAAAEAAAADAACAC4AAAAEAAAADQACAC4AAAAEAAAADgAC" +
  "AC4AAAAEAAAAEAAQAAAAAAAEAAAAEQAOABAAAQAAAAAAAAABAC8AAQAAAAAAAQAIAHoAAQAAAAAAAgAHAIIAAQAAAAAA" +
  "AwATAKQAAQAAAAAABAAQAIkAAQAAAAAABQALAJkAAQAAAAAABgAPAHoAAQAAAAAABwABAC8AAQAAAAAACAABAC8AAQAA" +
  "AAAACQABAC8AAQAAAAAACgABAC8AAQAAAAAACwABAC8AAQAAAAAADAABAC8AAQAAAAAADQABAC8AAQAAAAAADgABAC8A" +
  "AQAAAAAAEAAIAHoAAQAAAAAAEQAHAIIAAwABBAkAAAACAC4AAwABBAkAAQAQAAAAAwABBAkAAgAOABAAAwABBAkAAwAm" +
  "AFQAAwABBAkABAAgAB4AAwABBAkABQAWAD4AAwABBAkABgAeAAAAAwABBAkABwACAC4AAwABBAkACAACAC4AAwABBAkA" +
  "CQACAC4AAwABBAkACgACAC4AAwABBAkACwACAC4AAwABBAkADAACAC4AAwABBAkADQACAC4AAwABBAkADgACAC4AAwAB" +
  "BAkAEAAQAAAAAwABBAkAEQAOABAASQBtAHAAbwByAHQAZQBkAFIAZQBnAHUAbABhAHIASQBtAHAAbwByAHQAZQBkACAA" +
  "UgBlAGcAdQBsAGEAcgBWAGUAcgBzAGkAbwBuACAAMAAuADEAIAA6ACAASQBtAHAAbwByAHQAZQBkACAAUgBlAGcAdQBs" +
  "AGEAckltcG9ydGVkUmVndWxhckltcG9ydGVkIFJlZ3VsYXJWZXJzaW9uIDAuMSA6IEltcG9ydGVkIFJlZ3VsYXIAAAAA" +
  "AAABAAMAAQAAAAwABAAgAAAABAAEAAEAAABD//8AAABB////wAABAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAQAEAQABAQEQSW1wb3J0ZWRSZWd1bGFyAAEBASf4GwD4HAL4HQP4HgSLi/m0+JwFHQAAAH0PHQAAAIQRix0A" +
  "AAC5EgAHAQEMHCQrLC0uVmVyc2lvbiAwLjFJbXBvcnRlZCBSZWd1bGFySW1wb3J0ZWRSZWd1bGFyQUJDAAAAAYsBjAGN" +
  "AAQBAQQSIC74iA74nNuLFffAiwWL+SgFDvic24sV98CLBYv5KAUO+JzbixX3wIsFi/koBQ4AAAAB9AAAAggAAAIIAAAC" +
  "CAAAAAAAAQAAAAAAAAABABAAAmVuAAA=";

const DUPES =
  "T1RUTwAKAIAAAwAgQ0ZGIJ9QS4IAAATgAAAApE9TLzJpKmOIAAABEAAAAGBjbWFwAAwAdQAABJQAAAAsaGVhZC5Wo5oA" +
  "AACsAAAANmhoZWEDIgFEAAAA5AAAACRobXR4BgQAAAAABYQAAAAMbHRhZ2V+AAQAAAWQAAAAEm1heHAAA1AAAAABCAAA" +
  "AAZuYW1lBcAD8gAAAXAAAAMhcG9zdAADAAAAAATAAAAAIAABAAAAAQAAI9caJ18PPPUAAwPoAAAAAOa6MBMAAAAA5row" +
  "EwBQAAABfAKUAAAAAwACAAAAAAAAAAEAAAMg/zgAAAIIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAADAABQAAADAAAAAwII" +
  "AfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAWFhYWABAAEEAQgMg/zgA" +
  "AAKUAAAAAAABAAAAAAGQApQAAAAAAAAAAAAzAmoAAAAEAAAAAAACAC4AAAAEAAAAAQAQAAAAAAAEAAAAAgAOABAAAAAE" +
  "AAAAAwAmAFQAAAAEAAAABAAgAB4AAAAEAAAABQAWAD4AAAAEAAAABgAeAAAAAAAEAAAABwACAC4AAAAEAAAACAACAC4A" +
  "AAAEAAAACQACAC4AAAAEAAAACgACAC4AAAAEAAAACwACAC4AAAAEAAAADAACAC4AAAAEAAAADQACAC4AAAAEAAAADgAC" +
  "AC4AAAAEAAAAEAAQAAAAAAAEAAAAEQAOABAAAQAAAAAAAAABAC8AAQAAAAAAAQAIAHoAAQAAAAAAAgAHAIIAAQAAAAAA" +
  "AwATAKQAAQAAAAAABAAQAIkAAQAAAAAABQALAJkAAQAAAAAABgAPAHoAAQAAAAAABwABAC8AAQAAAAAACAABAC8AAQAA" +
  "AAAACQABAC8AAQAAAAAACgABAC8AAQAAAAAACwABAC8AAQAAAAAADAABAC8AAQAAAAAADQABAC8AAQAAAAAADgABAC8A" +
  "AQAAAAAAEAAIAHoAAQAAAAAAEQAHAIIAAwABBAkAAAACAC4AAwABBAkAAQAQAAAAAwABBAkAAgAOABAAAwABBAkAAwAm" +
  "AFQAAwABBAkABAAgAB4AAwABBAkABQAWAD4AAwABBAkABgAeAAAAAwABBAkABwACAC4AAwABBAkACAACAC4AAwABBAkA" +
  "CQACAC4AAwABBAkACgACAC4AAwABBAkACwACAC4AAwABBAkADAACAC4AAwABBAkADQACAC4AAwABBAkADgACAC4AAwAB" +
  "BAkAEAAQAAAAAwABBAkAEQAOABAASQBtAHAAbwByAHQAZQBkAFIAZQBnAHUAbABhAHIASQBtAHAAbwByAHQAZQBkACAA" +
  "UgBlAGcAdQBsAGEAcgBWAGUAcgBzAGkAbwBuACAAMAAuADEAIAA6ACAASQBtAHAAbwByAHQAZQBkACAAUgBlAGcAdQBs" +
  "AGEAckltcG9ydGVkUmVndWxhckltcG9ydGVkIFJlZ3VsYXJWZXJzaW9uIDAuMSA6IEltcG9ydGVkIFJlZ3VsYXIAAAAA" +
  "AAABAAMAAQAAAAwABAAgAAAABAAEAAEAAABC//8AAABB////wAABAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAQAEAQABAQEQSW1wb3J0ZWRSZWd1bGFyAAEBASf4GwD4HAL4HQP4HgSLi/m0+JwFHQAAAHkPHQAAAH4Rix0A" +
  "AACkEgAFAQEMHCQrLFZlcnNpb24gMC4xSW1wb3J0ZWQgUmVndWxhckltcG9ydGVkUmVndWxhckEAAAABiwGLAAMBAQQS" +
  "IPiIDvic24sV98CLBYv5KAUO+JzbixX3wIsFi/koBQ4B9AAAAggAAAIIAAAAAAABAAAAAAAAAAEAEAACZW4AAA==";

function decode(base64: string): ArrayBuffer {
  return Uint8Array.from(Buffer.from(base64, "base64")).buffer;
}

export const threeGlyphFont = (): ArrayBuffer => decode(THREE);
export const duplicateNameFont = (): ArrayBuffer => decode(DUPES);
